// <auto-generated />
using MedicalRecords.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalRecords.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123130308_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiseasePatient", b =>
                {
                    b.Property<int>("DiseasesId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.HasKey("DiseasesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("DiseasePatient");

                    b.HasData(
                        new
                        {
                            DiseasesId = 2,
                            PatientsId = 1
                        },
                        new
                        {
                            DiseasesId = 3,
                            PatientsId = 1
                        },
                        new
                        {
                            DiseasesId = 4,
                            PatientsId = 2
                        },
                        new
                        {
                            DiseasesId = 7,
                            PatientsId = 2
                        },
                        new
                        {
                            DiseasesId = 1,
                            PatientsId = 3
                        },
                        new
                        {
                            DiseasesId = 5,
                            PatientsId = 3
                        },
                        new
                        {
                            DiseasesId = 2,
                            PatientsId = 4
                        },
                        new
                        {
                            DiseasesId = 10,
                            PatientsId = 4
                        },
                        new
                        {
                            DiseasesId = 3,
                            PatientsId = 5
                        },
                        new
                        {
                            DiseasesId = 5,
                            PatientsId = 5
                        },
                        new
                        {
                            DiseasesId = 8,
                            PatientsId = 5
                        },
                        new
                        {
                            DiseasesId = 6,
                            PatientsId = 6
                        },
                        new
                        {
                            DiseasesId = 9,
                            PatientsId = 7
                        },
                        new
                        {
                            DiseasesId = 10,
                            PatientsId = 7
                        },
                        new
                        {
                            DiseasesId = 7,
                            PatientsId = 8
                        },
                        new
                        {
                            DiseasesId = 2,
                            PatientsId = 9
                        },
                        new
                        {
                            DiseasesId = 3,
                            PatientsId = 9
                        },
                        new
                        {
                            DiseasesId = 8,
                            PatientsId = 9
                        },
                        new
                        {
                            DiseasesId = 4,
                            PatientsId = 10
                        });
                });

            modelBuilder.Entity("MedicalRecords.Domain.Models.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Острое инфекционное заболевание дыхательных путей",
                            Name = "Грипп",
                            Symptoms = "Высокая температура, головная боль, слабость, боль в мышцах"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Повышенное артериальное давление",
                            Name = "Гипертония",
                            Symptoms = "Головная боль, головокружение, шум в ушах"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Эндокринное заболевание, связанное с нарушением усвоения глюкозы",
                            Name = "Сахарный диабет",
                            Symptoms = "Жажда, частое мочеиспускание, усталость"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Хроническое воспалительное заболевание дыхательных путей",
                            Name = "Астма",
                            Symptoms = "Одышка, кашель, хрипы"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Воспаление суставов",
                            Name = "Артрит",
                            Symptoms = "Боль в суставах, скованность, припухлость"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Воспаление слизистой оболочки желудка",
                            Name = "Гастрит",
                            Symptoms = "Боль в желудке, тошнота, изжога"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Неврологическое заболевание",
                            Name = "Мигрень",
                            Symptoms = "Сильная головная боль, тошнота, светочувствительность"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Дегенеративное заболевание позвоночника",
                            Name = "Остеохондроз",
                            Symptoms = "Боль в спине, ограничение подвижности"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Воспаление легких",
                            Name = "Пневмония",
                            Symptoms = "Кашель, высокая температура, боль в груди"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Повышенная чувствительность иммунной системы",
                            Name = "Аллергия",
                            Symptoms = "Чихание, зуд, сыпь, отеки"
                        });
                });

            modelBuilder.Entity("MedicalRecords.Domain.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Specialization");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Иван",
                            LastName = "Петров",
                            LicenseNumber = "LIC001",
                            Specialization = "Кардиолог"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Мария",
                            LastName = "Иванова",
                            LicenseNumber = "LIC002",
                            Specialization = "Невролог"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Алексей",
                            LastName = "Сидоров",
                            LicenseNumber = "LIC003",
                            Specialization = "Терапевт"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ольга",
                            LastName = "Кузнецова",
                            LicenseNumber = "LIC004",
                            Specialization = "Дерматолог"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Сергей",
                            LastName = "Васильев",
                            LicenseNumber = "LIC005",
                            Specialization = "Офтальмолог"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Екатерина",
                            LastName = "Николаева",
                            LicenseNumber = "LIC006",
                            Specialization = "Педиатр"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Дмитрий",
                            LastName = "Орлов",
                            LicenseNumber = "LIC007",
                            Specialization = "Хирург"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Анна",
                            LastName = "Захарова",
                            LicenseNumber = "LIC008",
                            Specialization = "Гинеколог"
                        });
                });

            modelBuilder.Entity("MedicalRecords.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 45,
                            DoctorId = 1,
                            FirstName = "Андрей",
                            LastName = "Смирнов",
                            PhoneNumber = "+79123456789"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            DoctorId = 2,
                            FirstName = "Елена",
                            LastName = "Попова",
                            PhoneNumber = "+79123456780"
                        },
                        new
                        {
                            Id = 3,
                            Age = 50,
                            DoctorId = 3,
                            FirstName = "Дмитрий",
                            LastName = "Козлов",
                            PhoneNumber = "+79123456781"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            DoctorId = 1,
                            FirstName = "Наталья",
                            LastName = "Морозова",
                            PhoneNumber = "+79123456782"
                        },
                        new
                        {
                            Id = 5,
                            Age = 60,
                            DoctorId = 3,
                            FirstName = "Виктор",
                            LastName = "Орлов",
                            PhoneNumber = "+79123456783"
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            DoctorId = 4,
                            FirstName = "Светлана",
                            LastName = "Волкова",
                            PhoneNumber = "+79123456784"
                        },
                        new
                        {
                            Id = 7,
                            Age = 42,
                            DoctorId = 5,
                            FirstName = "Михаил",
                            LastName = "Лебедев",
                            PhoneNumber = "+79123456785"
                        },
                        new
                        {
                            Id = 8,
                            Age = 29,
                            DoctorId = 6,
                            FirstName = "Ольга",
                            LastName = "Семенова",
                            PhoneNumber = "+79123456786"
                        },
                        new
                        {
                            Id = 9,
                            Age = 55,
                            DoctorId = 7,
                            FirstName = "Александр",
                            LastName = "Павлов",
                            PhoneNumber = "+79123456787"
                        },
                        new
                        {
                            Id = 10,
                            Age = 38,
                            DoctorId = 8,
                            FirstName = "Ирина",
                            LastName = "Федорова",
                            PhoneNumber = "+79123456788"
                        });
                });

            modelBuilder.Entity("DiseasePatient", b =>
                {
                    b.HasOne("MedicalRecords.Domain.Models.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalRecords.Domain.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalRecords.Domain.Models.Patient", b =>
                {
                    b.HasOne("MedicalRecords.Domain.Models.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalRecords.Domain.Models.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
